preset: psr2

enabled:
  - align_double_arrow
  - align_equals
  - ereg_to_preg
  - extra_empty_lines
  - join_function
  - newline_after_open_tag
  - no_empty_lines_after_phpdocs
  - object_operator
  - ordered_use
  - phpdoc_indent
  - phpdoc_scalar
  - remove_lines_between_uses
  - return
  - short_array_syntax
  - short_echo_tag
  - single_blank_line_before_namespace
  - single_quote
  - standardize_not_equal
  - whitespacy_lines
